version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DATABASE_USERNAME=${DATABASE_USERNAME}
        - DATABASE_PASSWORD=${DATABASE_PASSWORD}
        - DATABASE_NAME=${DATABASE_NAME}
        - DATABASE_HOST=${DATABASE_HOST}
    env_file: .env
    ports:
      - '${EXPOSED_PORT}:${PORT}'
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
